<?php
/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<form class="form form-edit-hobby"
      action="<?= $block->escapeUrl($block->getUrl('customer/hobby/editPost')) ?>"
      method="post"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Hobby Information')) ?></span></legend><br>
        <?= $block->getLayout()
            ->createBlock(\Ay\CustomerGraphQl\Block\Widget\Hobby::class)
            ->setHobby($block->getCustomer()->getCustomAttribute('hobby'))
            ->toHtml()
?>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>

